version: '3'
services:
  python-cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python-cli
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
       - ./:/app

networks:
    default:
      external:
        name: madlabsnet
  